/** Entidades financieras de Colombia. Nequi y Daviplata primero (las más usadas). */
export const COLOMBIA_BANKS = [
  "Nequi",
  "Daviplata",
  "Bancolombia",
  "Banco de Bogotá",
  "Davivienda",
  "BBVA Colombia",
  "Banco de Occidente",
  "Banco Popular",
  "Banco Caja Social",
  "Banco AV Villas",
  "Itaú Colombia",
  "Scotiabank Colpatria",
  "Banco Agrario",
  "Banco GNB Sudameris",
  "Banco Falabella",
  "Banco Pichincha",
  "Banco Serfinanza",
  "Bancoomeva",
  "Banco W",
  "Bancamía",
  "Banco Mundo Mujer",
  "Banco Finandina",
  "Banco Cooperativo Coopcentral",
  "Confiar Cooperativa Financiera",
  "Lulo Bank",
  "Nu Colombia",
  "Movii",
  "Dale!",
  "Rappipay",
  "Ualá",
  "Otro",
] as const;
